services:
  - type: pserv
    name: xeno-db
    databaseName: xeno_crm
    user: postgres

  - type: redis
    name: xeno-redis

  - type: web
    name: xeno-frontend
    runtime: node
    buildCommand: "npm install && npx prisma generate && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: xeno-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: xeno-redis
          property: connectionString

      - key: GROQ_API_KEY
        sync: false

  - type: worker
    name: xeno-worker
    runtime: node
    buildCommand: "npm install && npx prisma generate"
    startCommand: "npm run worker"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: xeno-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: xeno-redis
          property: connectionString